# Generated by Django 5.0.2 on 2024-02-18 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField(verbose_name='Кол-во каллорий на 100 грамм')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview_image', models.ImageField(upload_to='images/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_minutes', models.IntegerField(default=1, help_text='В минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления')),
                ('category', models.CharField(choices=[('B', 'Завтрак'), ('L', 'Обед'), ('D', 'Ужин')], max_length=1, verbose_name='Приём пищи')),
                ('ingredients', models.ManyToManyField(to='main_app.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'ordering': (('-created_at',),),
            },
        ),
    ]
